# -*- coding: utf-8 -*-
"""pyspark_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i-CfvlANRWHrNYrw_6Kf3H10gCfBuwQ8
"""

import pandas as pd
import numpy as np
import spark as sp

!pip install pyspark

from pyspark.sql import SparkSession
spark = SparkSession.builder.master('local[*]').getOrCreate()
spark = SparkSession.builder.appName('sol').getOrCreate()

import pandas as pd
import numpy as np
pd_temp = pd.DataFrame(np.random.random(10))

spark_temp = spark.createDataFrame(pd_temp)